### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/dom#100]
```javascript
DOM.select(selector).elements().tap(console.log)
```

logs `[]` endlessly until `RangeError: Maximum call stack size exceeded`.

**Comment by TylorS** [comment]
I can't seem to recreate this @Frikki 

https://esnextb.in/?gist=5a45e425779a42cab5f55e8f014f0dfd

**Comment by TylorS** [comment]
https://esnextb.in/?gist=5a45e425779a42cab5f55e8f014f0dfd

This demonstrates it, but it's not really an issue with @motorcycle/dom, but an issue with Cycle in general. 
When you're writing applications you need to be aware of not creating infinite loops like this. 
It's possible to avoid this error with combinators like `.take(1)`, `.skipRepeats()`, `skipRepeatsWith(compare)` or maybe `.filter(predicate)`

**Comment by TylorS** [comment]
As per our own private discussion, this is expected behavior. Closing for now
