### ISSUE TITLE
Clean up rootElem$

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/dom#23]
# Overview
Clean up [rootElem$](https://github.com/motorcyclejs/dom/blob/develop/src/index.js#L153-L166) to make better use of *most*.

# Motivation
Currently there is no way to end the stream or catch errors.

**Comment by Frikki** [comment]
*Continued from @TylorS https://github.com/motorcyclejs/dom/pull/24#issuecomment-164272191*

> Okay, so I know this was originally my idea, but I'm second guessing it now.

> It's actually impossible to force view$ to end. Even using most.empty() or most.never() because the Subject created in core never ends.
> Catching errors is useless without passing it along to core in some way as well as there is no ability to continue after the error reliably, and is probably not desired behavior in many applications.
> I'm beginning to think it's best to allow any thrown errors to be handled by the application developer instead.

> Thoughts?

For the reasons that you mentioned, I agree that end users should handle errors. It’s just important to document which errors to expect.

**Comment by TylorS** [comment]
Well, they should only be errors defined by the develop. For example:
```js
function main(sources) {
  return {
    DOM: most.just(1).map(() => {
      throw new Error('error')
    }) 
  }
}

run(main, {
  DOM: makeDOMDriver('#app')
})
```

**Comment by TylorS** [comment]
At least the errors that are within scope of this feature.

**Comment by Frikki** [comment]
Well, then there’s no cow on the ice (translation: no worries). Let’s close this issue and kill the PR https://github.com/motorcyclejs/dom/pull/24
