### ISSUE TITLE
more intelligent event listening

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/dom#4]
With the fix proposed in #2 to workaround current [Snabbdom behavior](https://github.com/paldepind/snabbdom/issues/36) the performance test has noticeably more long-running frames.

A better solution to when event handlers are added and removed is needed to counteract this. Any help and/or ideas is warmly welcomed.

**Comment by TylorS** [comment]
I just implemented a DOM.selectBy API in the add-selectBy branch, that adds the following
```js
DOM.selectBy.id('id')
DOM.selectBy.className('class')
DOM.selectBy.tageName('tagName')
```

Using DOM.selectBy.className('class') in the performance test results in a small but noticeable performance improvement. 

Like to get some feedback on this before merging this.

**Comment by TylorS** [comment]
With the implementation of isolateSource and isolateSink to work with `@cycle/isolate` it's now possible to do multiple 'select()'s
```js
DOM.select('.selector1').select('#selector2')
```

Should the proposed API above be available at all times?

```js
DOM.selectBy.className('selector').selectBy.id("id').select('#id2')
```

**Comment by Frikki** [comment]
It should. But I’m not sure I like the API `selectBy`. I think I may better like `selectById`, `selectByClass`, etc.

**Comment by TylorS** [comment]
Yeah, I agree with you.

**Comment by TylorS** [comment]
Okay, so currently we have removed the need for querySelectorAll by moving to snabbdom-selector.
I see a possibility for reusing event listeners by making use of `skipRepeatsWith()`.
https://github.com/motorcyclejs/dom/blob/develop/src/index.js#L119 would become something like
```js
function skipSameNode(oldElements, elements) {
  if (oldElements.length !== elements.length) {
    return false
  }
  oldElements.forEach((node, i) => {
    if (node.innerHTML !== elements[i].innerHTML) {
      return false
    }
  })
 return true
}

makeEventsSelector(element$.map(mapToElement).skipRepeatsWith(skipSameNode))
```

The skipSameNode function is rather crude, but should show the general idea.

On #31 @Frikki brought up an example which might counteract our good intentions here.

Should it be assumed a 'best practice' to do something like this instead
```js
most.merge(
  DOM.select('.example').events('keyup'),
  DOM.select('.example').events('keydown')
)
```

**Comment by Frikki** [comment]
I’d say, that it is not unusual practice, e.g.:

```js
const focused$ = most.merge(
    DOM.select('.example').events('focus', true).map(true),
    DOM.select('.example').events('blur', true).map(false),
  )
  .startWith(false)
```

**Comment by TylorS** [comment]
From this issue cyclejs/cycle-dom#85 we are experiencing large amounts of lag when there are large amounts of DOM nodes with event listeners.

One of the possible solutions I uncovered is through using event delegation. I'm going to work on getting this working in Motorcycle-DOM as well, and we can attempt to weigh the pros and cons.

**Comment by TylorS** [comment]
Closing this now, I think we are about as optimized as we can get.

**Comment by staltz** [comment]
:+1:
