### ISSUE TITLE
browser performance test malfunctioning

### ISSUE THREAD

**Issue by Frikki** [motorcyclejs/dom#44]
### Overview

The slider handle leaves a ghost trail when dragged quickly. Logos are not updated correctly. Sometimes they can stay a second or two before being removed. When slider is dragged to zero, there’s still one logo; sometimes more; four has been documented.

### Motivation

We need to test performance, and the test serves a litmus test that the DOM driver works as intended.

**Comment by TylorS** [comment]
Have you been able test the updates?

**Comment by TylorS** [comment]
@Frikki If you feel the recent updates are acceptable, please close this.

**Comment by TylorS** [comment]
I'm going to close this from our private discussions it seems to be solved @Frikki 

If you feel otherwise please reopen.
