### ISSUE TITLE
add makeDOMDriver and mark as deprecated

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/dom#50]
# Overview

Add a convenience function `makeDOMDriver` for those transitioning from Cycle.js and mark
as deprecated
Add documentation that makeDOMDriver is deprecated.

# Possible solution
```js
//index.js
import makeDomDriver from './makeDomDriver'

export function makeDOMDriver(container, modules) {
  console.warn('makeDOMDriver is a deprecated function. Please update to makeDomDriver.')
  return makeDomDriver(container, modules)
}
```

**Comment by staltz** [comment]
:-1: Let's discuss these types of big decisions before "just doing it": https://github.com/motorcyclejs/dom/commit/8aeaa425258d7d0b869aa2d2f8f872b601a56a99#commitcomment-15117588

**Comment by Frikki** [comment]
I agree with @staltz
