### ISSUE TITLE
Revert makeDomDriver back to makeDOMDriver

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/dom#51]
# Overview
Revert the naming of makeDomDriver -> makeDOMDriver
Revert the documentation to reflect the API change
Update the usage in the tests

# Motivation
Because we love you @staltz 

# References
https://github.com/motorcyclejs/dom/commit/8aeaa425258d7d0b869aa2d2f8f872b601a56a99

**Comment by Frikki** [comment]
Yes, we love you @staltz :sparkling_heart:

**Comment by staltz** [comment]
> Yes, we love you @staltz :sparkling_heart:

It's the Christmas spirit in the air :christmas_tree: :santa: :heart:
