### ISSUE TITLE
Options object from makeDOMDriver()

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/dom#57]
Currently `makeDOMDriver()` accepts a `container` and an array of snabbdom modules to load.
```js
makeDOMDriver('.selector', [
  require('snabbdom/modules/props'),
  require('snabbdom/modules/style')
])
```

I'd like to make the second parameter an optional object. i.e.
```js
makeDOMDriver('.selector', {
  modules: [
    require('snabbdom/modules/props'),
    require('snabbdom/modules/style')
  ]
})
```
in order to gain flexibility in the future without the needing to further break the API. We are pre-1.0 now, and I would think it better now than later.

**Comment by staltz** [comment]
:+1: 

> We are pre-1.0 now, and I would think it better now than later.

And agreed.

**Comment by TylorS** [comment]
Cool, I'll make the possible changes soon. :+1:
