### ISSUE TITLE
Add option for a static vTree.

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/dom#58]
The is a small part of my reasoning for  #57 

# Overview

If we decided to accept #57, I would like to add an option for a static vTree
By a static vTree, I mean a vTree which does not have any nested streams. This can avoid the need for transposition for further performance enhancements in such scenarios that the view is powered by other sources like a database. vTreeParser() is by far one of the most expensive functions in this library, because of all of the recursion, and most.combine() is one of the costlier operators most has.

# Potential API

```
makeDOMDriver('.selector', {staticVTree: true})
```

# Possible solution
[this line](https://github.com/motorcyclejs/dom/blob/develop/src/makeDOMDriver.js#L60) would become 
```js
.map(vTree => vTreeParser(vTree, staticVTree))
```
And [here](https://github.com/motorcyclejs/dom/blob/develop/src/vTreeParser.js#L16-L17) would become
```js
(vTree, staticVTree) => {
  if (staticVTree) {
    return most.just(vTree)
  } else if (!vTree) {
```

**Comment by staltz** [comment]
Hmm, I'm not so happy about this API. It's essentially an option for optimizing performance, but it's a *catches-all* option. In a large app, it's quite likely you will eventually want to use transposition, but if the option is off, then you can't. Usually, performance is a bottleneck at specific parts of the whole tree which are updated constantly and heavily. Is there anyway we can allow such local optimization to be opt-in?

**Comment by TylorS** [comment]
Yes actually, but I'm not sure how expensive the check would be. The way that Snabbdom's `h()` is setup `h(selector, data, children)`, data is a place for extending behavior. We could easily add an option we check for. 

```js
h('div', {static: true}, [])
```

I would imagine this meaning 'starting here, my children and I do not need to be transposed'.

**Comment by TylorS** [comment]
The above would not affect the rendered output either. Just in case you were wondering.

**Comment by TylorS** [comment]
The proposed solution would just become this
```js
vTree => {
  if (vTree.data && vTree.data.static) {
      return most.just(vTree)
    } else if (!vTree) {
```

**Comment by staltz** [comment]
That sounds better

**Comment by TylorS** [comment]
Agreed, It would be much more flexible.
