### ISSUE TITLE
How to render only parts of container node ?

### ISSUE THREAD

**Issue by mamciek** [motorcyclejs/dom#73]
Let's suppose I have the following HTML:
```
<div id="app">
  <input id="search" type="text"/>
  <div id="autocomplete"></div>
</div>
```
and following app:
```
function main({DOM}) {
   const input$ = DOM.select('#search').events('keyup')...
   const response$ = <stream of responses from HTTP driver>

   const autocomplete$ = response$.map(res => ul(res.suggestions.map(s => li(s))))
   //autocomplete$ contains only vtree for the contents of #autocomplete div
   return {DOM: autocomplete$}
}

run(main, {DOM: makeDOMDriver('#app')})
```

how can i stream vtree into the #autocomplete div without removing or rerendering of input#search ?

**Comment by TylorS** [comment]
Hmm this isn't really supported the way things are now. The way I would recommend is by rendering the input as well. Maybe something like
```js
const prependSearch = autocomplete => div([
  input('#search', {}, []),
  autocomplete
])

return {DOM: autocomplete$.map(prependSearch)}
```

**Comment by staltz** [comment]
Please make questions in the gitter chat or in Stackoverflow :)

**Comment by TylorS** [comment]
I don't believe there is any way to achieve this with the way snabbdom, or any virtual-dom implementation that I can find, works currently.
