### ISSUE TITLE
Wrap Top Level Element

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/dom#8]
The current behavior is to replace the container given to `makeDOMDriver(container)`.

Given this as input
```js
h('div', {}, ['Hello, world'])
```
will make
```html
<div id='app'>Loading...</div>
```
equal
```html
<div>Hello, world</div>
```

However Cycle-DOM wraps the top element, in this example that would be  `#app`. Given the same input it would output
```html
<div id='app'>
  <div>Hello, world</div>
</div>
```

I'd like to gather a consensus on whether this behavior should be implemented or be left the way it is.

**Comment by TylorS** [comment]
Benefits I see of wrapping the virtual trees with the root element:
- Ease of migration from Cycle -> Motorcycle
- Support for any styles that may be applied to the root Element

Benefits I see for the current behavior:
- Allows modification of the root element

**Comment by Frikki** [comment]
I think the reason given by @staltz in this commit https://github.com/cyclejs/cycle-dom/commit/866a5b37e8422e599804cfa56892347151b8a350

> Diff and patch root element is not anymore a child of the
given container (to the DOM Driver). It is now the given
container itself. Diff and patch will not override and destroy
the identity of the given container. Instead, it will preserve it.
In fact, the given container element is parsed to a vtree, and is
used as the first vtree in the diff & patch sequence. This enables
avoiding to rerender the same tree client-side if it was already
rendered server-side, which saves processing power especially on
mobile devices. The semantics of the root element Observable,
get(':root'), for the DOM Driver has also changed: the first
emission is what was given as the container. This is important for
attaching event listeners.

... is such a strong argument that the implementation ought to be the same in *motorcycle-dom*.

**Comment by TylorS** [comment]
It's kind of hard to find any reason to disagree with all of that.

**Comment by Frikki** [comment]
Shall we stick with the same implementation?

**Comment by TylorS** [comment]
I'm starting to think it may be best. I've tried starting for scratch multiple times, but no luck. Probably should close this PR and keep the issue open for the future. Any objections to that?

**Comment by Frikki** [comment]
No objections. Just remove the milestone from the issue.
