### ISSUE TITLE
hJSX helper

### ISSUE THREAD

**Issue by Risto-Stevcev** [motorcyclejs/dom#88]
I think the hJSX helper should be added into @motorcyclejs/dom

**Comment by TylorS** [comment]
I would generally suggest using babel plugins to handle this. Snabbdom is rather peculiar in some way, so I would sugest that along with snabbdom-jsx.

https://github.com/motorcyclejs/dom/blob/develop/.babelrc#L6-L7
https://github.com/motorcyclejs/dom/blob/develop/test/browser/render.js#L8

**Comment by TylorS** [comment]
Also with a babel-plugin like https://github.com/tleunen/babel-plugin-module-alias
You wouldn't have to import html from snabbdom-jsx over and over

**Comment by Risto-Stevcev** [comment]
Could motorcyclejs/dom provide an alias for `snabbdom-jsx`'s `html` as `hJSX`?

Or would that deviate too much from the original `hJSX`. It seems as though it's doing the same kind of thing: `hJSX` and `snabbdom-jsx`'s `html` are both pragmas for the `transform-react-jsx` babel plugin.

**Comment by TylorS** [comment]
Part of the issue with it is snabbom-jsx has 3 different pragmas https://github.com/yelouafi/snabbdom-jsx/blob/master/snabbdom-jsx.js#L93

**Comment by TylorS** [comment]
Overall I don't work with JSX, and I don't want there to be much of an opinion on it in my library.

There is also https://github.com/finnsson/babel-snabbdom-jsx

**Comment by TylorS** [comment]
Though I have made a small effort to ensure it works: https://github.com/motorcyclejs/dom/blob/develop/test/browser/render.js#L48

**Comment by Risto-Stevcev** [comment]
It's not really 3 pragmas though, it's just the `html` pragma that's the `hJSX` equivalent. The `svg` pragma is for defining `svg` nodes with it's given namespace, and the `JSX` one just returns the function itself in case you want the flexibility to handle some other `XML` subtype.

As far as I can tell `snabbdom-jsx` the only currently viable alternative. It doesn't seem like `babel-snabbdom-jsx` works and/or is being actively maintained.

I think motorcyclejs should be in parity with cyclejs as much as it can be and I think it should be considered. But if you're strictly opposed to it then I think `snabbdom-jsx` should at least be suggested in the docs for people switching from cyclejs.

**Comment by TylorS** [comment]
This is something I've let sit for a long time, I've not used JSX at all, and now that this is ported to TypeScript I suppose this is an issue that'd have to be dealt with by TSX and whatever mechanisms it uses. I'm going to open another issue related to creating an example that uses TSX.
