### ISSUE TITLE
Thunk export is different from what is described by Snabbdom

### ISSUE THREAD

**Issue by axefrog** [motorcyclejs/dom#97]
The Motorcycle DOM documentation says to refer to Snabbdom's documentation on thunks, but exports a thunk function with a different signature than what is described in Snabbdom's documentation.

Motorcycle exports: `function (name, fn, ...args)`
Snabbdom exports `function (name, key, render, ...args)`.

**Comment by TylorS** [comment]
This has actually been fixed some time ago :)
